### ISSUE TITLE
Get tips back in!

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#902] opened 2017-07-07 09:16 UTC
+ [x] confirm mark up rules for @katyedwards

**Comment by markwilliamfirth** [comment] 2017-07-10 09:03
We will need further details on this issue - to be confirmed on the call with Katy

**Comment by katyedwards** [comment] 2017-07-10 11:07
Hi @RobStallion as mentioned, I just need to confirm the correct mark up so I can enter the tips and get them displaying correctly first time - as _we_ can't edit or delete the tips once they are in.

Is this the correct way to enter a tip:
![screenshot 2017-07-10 12 05 31](https://user-images.githubusercontent.com/24604903/28015490-1be4d578-6568-11e7-8bca-4e5d03bbb585.png)

To get a live tip hashtag which links to all the tips and a live 'category' hashtag (e.g. TakeNotice) which links to all the tips for that category - which looks like below:

![screenshot 2017-07-10 12 01 20](https://user-images.githubusercontent.com/24604903/28015523-3d55dd1a-6568-11e7-8540-c4436cb4e8de.png)

**Comment by markwilliamfirth** [comment] 2017-07-11 11:51
@katbow could you give @RobStallion an example of how a tip should be entered by an admin?

**Comment by RobStallion** [comment] 2017-07-12 09:03
@katyedwards the image you posted on how the tips should be formatted is almost exactly right.

![image](https://user-images.githubusercontent.com/15571853/28109972-cce509e8-66e8-11e7-9650-c0220ccddb79.png)

The only thing that needs to be different is that there should be no spaces between the `#` and the words `Tip` or `TakeNotice`

**Comment by katyedwards** [comment] 2017-07-12 09:09
Great thanks.  I'll close this and will get adding this afternoon or tomorrow.

**Closed by katyedwards** 2017-07-12 09:09 UTC
Labels: priority-1, question, T25m
