### ISSUE TITLE
HL Staging Site is down

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#986] opened 2017-08-17 08:14 UTC
![screenshot 2017-08-17 09 12 45](https://user-images.githubusercontent.com/24604903/29402282-4cbacd10-832c-11e7-98c0-39eb8c386f79.png)

Has been down since Tues last week (8th) - possibly before, but that was when it was noticed.

As far as we are aware, no one was working on it when it went down

**Comment by katyedwards** [comment] 2017-08-21 14:57
Sorted thanks!

**Comment by reddog** [comment] 2017-08-22 08:23
@RobStallion Thanks for getting the staging site back up and running.  As mentioned elsewhere, it is anticipated that SLaM IT will be handling support going forward.  As such, we need to build details / notes on what has/can go wrong and how to fix it.

Are you able to provide some notes on:

1.  how you identified what (in particular) wasn't working?
2.  how you resolved the issue?
3.  what has been changed to help prevent this particular issue recurring?

**Comment by markwilliamfirth** [comment] 2017-08-22 09:16
@reddog I think @RobStallion hadn't had a chance to update before this one was closed. In the standup Rob mentioned that he does not know what caused this and that it appeared as if the server had just been 'turned off' and the fix was to switch it back on.

@RobStallion could you elaborate further as to any more detail as to the cause of this and how we can prevent this from happening again in future?

**Comment by reddog** [comment] 2017-08-22 09:19
@markwilliamfirth Sorry for missing yesterday's standup and thanks for the update.

In terms of others supporting the app, understanding what *turned off* means, how to fix it, and how to *help* prevent that particular issue from recurring would be a great devops step forwards.

**Comment by markwilliamfirth** [comment] 2017-08-22 09:24
@reddog I didn't realise before but it looks like @katbow has answered your questions with the linked PR above (https://github.com/healthlocker/healthlocker/pull/989)

**Comment by markwilliamfirth** [comment] 2017-08-22 09:25
@katbow @RobStallion can we add a summary comment to this issue addressing David's points before finally closing?

**Comment by reddog** [comment] 2017-08-22 09:32
@markwilliamfirth Thanks for that link - I hadn't spotted that.

Thanks for your notes @katbow.  I'm not quite sure what 

> the plug wasn't working

means.  Could you expand a little?

The PR also mentions that

> Oxleas templates were loading

How did Oxleas templates get on to the SLaM staging site?  It seems like we should do some investigation in to that to ensure that doesn't happen in the future.

**Comment by katbow** [comment] 2017-08-22 09:44
@reddog there was a plug that was made to identify whether the app was running in oxleas or healthlocker environments. I missed a case in the plug, so it was going to the incorrect one. Because of this, the oxleas templates were trying to load. The templates aren't actually present, and I should have said **trying** to load, since the error was caused due to them not existing. This plug was done originally as a way to make the app generic, but @RobStallion & I changed slightly how these were loaded in so that there is better separation.

This won't be a problem again because:
* Right now the plug always identifies the environment as HL (temporary measure until point 2)
* The plug will be removed from Healthlocker repo so it won't be possible to load any other templates or set the environment incorrectly.

**Comment by reddog** [comment] 2017-08-22 11:43
@katbow Thanks very much for expanding on that.

Does this mean that SLaM's Healthlocker has been re-deployed at some point?  Was that done knowingly or accidentally?  I don't think we aware of any planned-for deployments to SLaM's HL since the initial deployment and bug fixes around that time.

I have previously raised the potential risk of mis-deploying to an incorrect environment (or deploying with incorrect environment variables set).  It would be useful to understand what measures are in place to protect against mis-deployments.

**Comment by katbow** [comment] 2017-08-22 17:13
To clarify the discussion in the call:

What I understood is a concern that someone deploying the app could type in to `deploy staging` when they mean to `deploy test`. However, the 2 configurations would **not** be included in the same repo. Each repo will have it's own [edeliver config](https://github.com/healthlocker/healthlocker/blob/master/.deliver/config#L3) which specifies the server to deploy to. So it would not be an option for a developer to deploy to both the staging & test servers from the same repo. 

So, if someone is working on a repo for the test application, they could only deploy to the test server. Currently there is only one repo for oxleas which deploys to the test server. There would be a separate repo for staging which has it's own configuration that is set to deploy the app to the staging server. 

How this would work for the development process is that the test repo would be a fork of the staging repo, and all the development would happen on the test repo. Once it was all deployed to the test server, and checked that it was working as intended (by ourselves, a senior developer reviewing the work, and yourselves checking it over on the test server), it would then need to be merged into the staging repo before a deploy could be done to the staging server.

**Comment by reddog** [comment] 2017-08-22 17:38
@katbow Thanks very much to you and @RobStallion for helping me through this issue on the call, and thanks for your notes here as well.

The `.deliver/config` file you linked to includes settings for build, staging and production.  In this example, they are all set to be the same IP address (quite possibly because there is only one environment at the moment).  However, it seems likely that the suggestion here is that different environments with their own IP addresses would be entered in the one, single, config file.

That being the case, it would be a "simple" case of human error to mis-type to deploy to production and not staging (for example).

Sorry, I wasn't aware of how you guys worked in terms of forking repos for development and then merge back in to the parent repo when complete - given that you've always been working from branches on the one repo, I guess I assumed that would remain the case.  However, if the full config file is still in the parent repo, the potential for mis-typing still exists, it would seem.

**Comment by RobStallion** [comment] 2017-08-22 18:50
@reddog No problem. Sorry it took so long for me to understand what it was you meant during the call. 

You are correct that the `.deliver/config` has multiple settings for different build types and you noticed that they all have the same address. The IP address in [this config](https://github.com/healthlocker/oxleas-adhd/blob/master/.deliver/config#L3) is the IP address belonging to the `oxleasadmin@Oxleas-HL-Test`
![image](https://user-images.githubusercontent.com/15571853/29580014-747ae440-876c-11e7-9827-bf421f59843f.png)
These will never be edited.

When it comes time to deploy the site to the `live/staging` environment, as @katbow mentioned, we will have a separate branch (protected branch that will only have changes merged in once the steps [mentioned by @katbow](https://github.com/healthlocker/healthlocker/issues/986#issuecomment-324092366) are complete) or a forked repo(same as mentioned above). For both the protected branch or forked repos options there would be a different `.deliver/config` file that would look fairly similar to the the one that was linked above but it will have **key** differences. The IP address will be pointing to the `live/site` `51.140.116.95` for all of the build, staging, and production settings. 
![image](https://user-images.githubusercontent.com/15571853/29581316-cad7e99c-8770-11e7-8c0d-cc330168b289.png)

It will not be possible to deploy from the `test` branch/repo to the `live` site as the IP address will not exist within it.

**Comment by markwilliamfirth** [comment] 2017-08-23 09:25
@reddog in reponse to the above and our call earlier, we can almost close this issue, we just need to work out when the error in the redeployment process occurred

@nelsonic - @katbow and @RobStallion didn't do this redeploy (on or before the 8th august) - can we check with you that it was you who did this redeployment? Once we know where the error occurred we can work out how to prevent it happening again in future.

**Comment by reddog** [comment] 2017-09-04 10:06
@nelsonic As per @markwilliamfirth's previous comment, are you able to provide any input on helping us understand (and hence fix) how this issue occurred?

**Comment by reddog** [comment] 2017-09-15 12:47
In terms of understanding more about what has happened when an issue occurs, it would be great to see if there is any more information available within the team on this?

**Comment by katbow** [comment] 2017-09-15 16:33
Note from call: I don't have any other comments on this myself.

**Comment by reddog** [comment] 2017-09-19 17:49
@iteles You said on the last call last week that you were going to get back to us on this?

**Comment by reddog** [comment] 2017-09-26 10:08
@iteles This issue is getting quite old now.  Is there anything further that @nelsonic can add or should we simply close this now?

Going forward it would be very useful to have information available much closer to the time of the incident.  Even if no further information is available, that in itself is useful to know (meaning that we should maybe look elsewhere).

**Comment by nelsonic** [comment] 2018-11-21 12:52
@katyedwards is this still an issue?

**Comment by ghost** [comment] 2018-11-22 10:32
Hi @nelsonic!  Nice to e-see you!

I think this can be closed now.  No more issues have occurred.  Thanks!

I should probably close a lot of the tech support issues too.  It took so long to get word that they were approved, life had moved on and I forgot about that.

Nicer to have a tidy repo though.

**Closed by ghost** 2018-11-22 10:32 UTC
Labels: priority-2

**Comment by nelsonic** [comment] 2018-11-22 13:32
@katyedwards great too see your name in my inbox. 📥 
Stoked that there haven't been any issues. ☀️ 
Thanks for closing. ✅ 
Hope you have a good afternoon. 🎉
