### ISSUE TITLE
Tips: Add category logo to top right corner of every tip whenever displayed 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#474] opened 2017-04-21 13:05 UTC
As a user, I can visually differentiate between the tips by noticing the different coloured logos.

+ [ ] Add category logo to top right corner of every tip whenever displayed 

<img width="591" alt="screen shot 2017-04-21 at 14 27 28" src="https://cloud.githubusercontent.com/assets/25012688/25279679/26e9ba0e-269f-11e7-913b-350f61172bfe.png">

Note from epic (need to be partials so can be reused for tips pages)

**Comment by indiamindwave24** [comment] 2017-04-24 11:39
All icons ending 'mini'
[5 ways to wellbeing icons.zip](https://github.com/healthlocker/healthlocker/files/951558/5.ways.to.wellbeing.icons.zip)

Should be centrally aligned vertically and horizontally to the corner of the 'tip box'
<img width="453" alt="screen shot 2017-04-24 at 12 39 37" src="https://cloud.githubusercontent.com/assets/25007700/25335478/1e4f1d14-28eb-11e7-8c0f-e14acd984d58.png">

**Comment by Cleop** [comment] 2017-04-25 09:33
- Got icon correctly positioned/ styled for hard coded example tips
- Now need to get url category type and select appropriate image according to this.
- <%= IO.puts(@conn.query_string) %> logs the query string e.g. tag=Connect

**Comment by indiamindwave24** [comment] 2017-04-25 12:32
<img width="837" alt="screen shot 2017-04-25 at 1 31 13 pm" src="https://cloud.githubusercontent.com/assets/25007700/25385312/907f9a78-29bb-11e7-9669-a6a4e2c64b01.png">
@Cleop The 'Give to Others' icon is not appearing

**Comment by katbow** [comment] 2017-04-25 12:53
@Cleop @indiamindwave24 I'll check this out

**Comment by katbow** [comment] 2017-04-25 12:55
![image](https://cloud.githubusercontent.com/assets/1287388/25386265/b13d109e-29be-11e7-954c-458a36929007.png)

I have it showing. what browser & version were you using please @indiamindwave24 ?

**Comment by katbow** [comment] 2017-04-25 13:07
@indiamindwave24 nevermind sorry, I see that the problem is. Problem on the live site but not when I run things locally.

**Comment by indiamindwave24** [comment] 2017-04-28 14:10
@katbow the images still take a long time to load - are these the new PNGs?

**Comment by katbow** [comment] 2017-04-28 14:39
not yet - only the toolkit has been changed.

I opened up a separate issue #539 for images in general. If you are happy the logos have been styled how described in the acceptance criteria, this can be closed as we will have the other issue to refer to for image loading times

**Closed** 2017-05-02 09:54 UTC
Labels: please-test, priority-2, T4h, user-feedback
