### ISSUE TITLE
Coping strategy styling

### ISSUE THREAD

**Issue by indiamindwave24** [healthlocker/healthlocker#551] opened 2017-05-02 12:41 UTC
As a user, I should see the coping strategies formatted similar to the rest of the site.

- [ ] Title 'Edit coping strategy' should be dark blue, not grey
- [ ] Text in text boxes should be correct font
- [ ] Subtitles (eg. Note down an action you can take to stay well.) should be left aligned
- [ ] All description text should be left aligned
- [ ] Padding should be consistent with rest of site (eg. width of text box)

**Comment by katbow** [comment] 2017-05-03 09:25
@indiamindwave24 I'm going to close this as duplicate of #488 and move this more detailed criteria to there 👍

**Closed by katbow** 2017-05-03 09:25 UTC
Labels: duplicate
