### ISSUE TITLE
Header title of sections

### ISSUE THREAD

**Issue by indiamindwave24** [healthlocker/healthlocker#509] opened 2017-04-26 09:11 UTC
- [ ] As a user I would like to see where I am on the site in the header and use this to navigate back.
![image](https://cloud.githubusercontent.com/assets/25007700/25426894/a19b8620-2a68-11e7-9ccc-62a1e3b8ea81.png)
- [ ] As a user I will only see the healthlocker logo in the header when I am logged out.

**Comment by indiamindwave24** [comment] 2017-04-26 09:11
@katbow can you please time estimate this?

**Comment by katbow** [comment] 2017-04-26 09:34
@indiamindwave24 done

**Comment by indiamindwave24** [comment] 2017-04-26 10:19
I cannot see it @katbow -- having 'tooklit' (for example) in header instead of HL logo?

**Comment by iteles** [comment] 2017-04-26 11:27
@indiamindwave24, @katbow was referring to the time estimate rather than the resolution itself 😊

**Comment by katbow** [comment] 2017-04-28 14:11
@indiamindwave24 I'm going to close this as duplicate of #466 and move that into this sprint

**Closed by katbow** 2017-04-28 14:11 UTC
Labels: priority-3, T1d
