### ISSUE TITLE
connecting with carers errors

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#671] opened 2017-05-19 07:44 UTC
Can you look into my mxxxxx.cxxxxxxxx@gmail.com account - I had the link 'Connect with the SLaM care team of someone I care for' available, so I tried to connect as Lisa's carer, I called myself John Sandoval. I got internal server error.  (I think this is the same or similar to what I highlighted a week or so ago - if you can remember.)

I then click on messaging, and it says I am messaging Evan Burn's care team. But a message that I had previously sent 2 days ago - probably as Evans carer - But this now has the name John Sandoval associated with it.

- I shouldn't have been able to connect with a second care team.
- I don't want to see a server error.
- 'Evan burns' in the messaging screen - is this hardcoded still?  or is there a bigger issue? 

<img width="667" alt="screen shot 2017-05-18 at 17 17 51" src="https://cloud.githubusercontent.com/assets/25012688/26237976/1578621c-3c6f-11e7-9393-35429f2ef418.png">

#278

**Comment by katbow** [comment] 2017-05-19 09:46
@MollieCourtenay 

> * I don't want to see a server error.

There's a fix for this in what I am working on now. It is because of the room creation not being done automatically when a carer/service user connects. 

> * 'Evan burns' in the messaging screen - is this hardcoded still? or is there a bigger issue?

It is not hardcoded anymore - it grabs the service user for that carer, but because this is connected to more than one Service User, it grabs the first service user you connected to. Adjusting this:

> * I shouldn't have been able to connect with a second care team.

should solve that issue. If you are a carer connected to only Lisa, then you should see her name. I connected to only her using test@mail.com & password. You can check it out there if you like.

So I guess the action here then is:
* Carers can only connect to one care team (i.e. can only care for one person)

Does that sound right?

**Comment by MollieCourtenay** [comment] 2017-05-19 13:26
<img width="688" alt="screen shot 2017-05-19 at 14 21 42" src="https://cloud.githubusercontent.com/assets/25012688/26249595/26444310-3c9f-11e7-9035-9766a94583d3.png">

@katbow  I see this on that  test@mail.com account.

**Comment by MollieCourtenay** [comment] 2017-05-19 13:27
I can also see the link to connect with a care team even though I am connected to Lisa's team. 

<img width="628" alt="screen shot 2017-05-19 at 14 27 15" src="https://cloud.githubusercontent.com/assets/25012688/26249648/542fa756-3c9f-11e7-9d3c-b870ff9c5f83.png">

**Comment by katbow** [comment] 2017-05-19 17:40
@MollieCourtenay the first part is fixed when my next pull request is merged in. I am going to put removing the link to connect as a carer when someone is already a carer into a separate issue.

**Comment by katbow** [comment] 2017-05-22 13:32
The bug we were seeing here is fixed and can be checked out now. If you connect as a new carer, then the account will connect & the rooms will be created automatically.

The other portion of this (to hide the connect to carer link if a carer is connected) is not a bug, but a feature change. Originally it was requested to remove only the connect to slam link #592 

> as a connected carer the link to be a SU is not visible to me

So I've added it to the top of the backlog as a new issue in #674

**Closed** 2017-05-23 16:27 UTC
Labels: bug, please-test, priority-1
